### ISSUE TITLE
python3 test failing, due to code from methylation branch

### ISSUE THREAD

**Issue by noblem** [broadinstitute/gdctools#60]
cd tests
make test3

... snip ...

Test dice: on subset of cohorts, to show CLI args override config file
set -o pipefail && env PYTHONPATH=.. /usr/local/bin/python3 ../gdctools/gdc_dice.py --config tcgaSmoketest.cfg  --projects TCGA-ACC TCGA-SKCM TCGA-ESCA 2>&1 | tee test_dice.log  | egrep "Dicing TCGA|date"
2017-09-15 23:48:27,330[INFO]: Mirror date: 2017_09_15
2017-09-15 23:48:27,331[INFO]: Dicing TCGA-ACC to sandbox/dice/TCGA/TCGA-ACC
/Users/mnoble/src.local/gdctools/util/checkError.sh test_dice.log
Traceback (most recent call last):
  File "../gdctools/gdc_dice.py", line 231, in execute
  File "../gdctools/gdc_dice.py", line 176, in dice
  File "../gdctools/gdc_dice.py", line 393, in dice_one
  File "../gdctools/gdc_dice.py", line 609, in usc_meth2magetab
  File "/Users/mnoble/src.local/gdctools/gdctools/lib/convert/tsv2magetab.py", line 41, in process
    writeCsvFile(filepath, csvfile_with_new_column_order)
  File "/Users/mnoble/src.local/gdctools/gdctools/lib/common.py", line 155, in writeCsvFile
  File "/Users/mnoble/src.local/gdctools/gdctools/lib/common.py", line 144, in rearrange_columns
TypeError: object of type 'map' has no len()
make[1]: *** [test_dice] Error 1
make: *** [test3] Error 2

**Comment by noblem** [comment]
The viability of Python3 testing has been re-established many times since this issue was first written, therefore marking closed.
