### ISSUE TITLE
Failed to mirror TCGA-BRCA

### ISSUE THREAD

**Issue by buchanae** [broadinstitute/gdctools#75]
```
gdc_mirror --projects TCGA-BRCA
2018-06-12 10:53:10,118[INFO]: GDC Mirror Version: 0.9.1 (GDCtools: 0.2.6)
2018-06-12 10:53:10,118[INFO]: Command: /mnt/gdc-download/venv/bin/gdc_mirror --projects TCGA-BRCA
2018-06-12 10:53:10,429[INFO]: Attempting to acquire lock: /mnt/gdc-download/gdctools_tmp/mirror/TCGA/.mirror.lock
2018-06-12 10:53:10,430[INFO]: Lock acquired.
2018-06-12 10:53:10,430[INFO]: Mirroring started for TCGA-BRCA (TCGA)
2018-06-12 10:53:10,430[INFO]: No categories specified, using GDC API to discover ALL available categories
2018-06-12 10:53:10,737[INFO]: Using 7 data categories: DNA Methylation,Transcriptome Profiling,Biospecimen,Simple Nucleotide Variation,Clinical,Raw Sequencing Data,Copy Number Variation
2018-06-12 10:53:10,737[INFO]: Mirroring data to ./gdctools_tmp/mirror/TCGA/TCGA-BRCA
2018-06-12 10:53:10,737[INFO]: Creating folder: ./gdctools_tmp/mirror/TCGA/TCGA-BRCA/Biospecimen
2018-06-12 10:53:15,396[INFO]: 3075 new Biospecimen files
2018-06-12 10:53:15,396[ERROR]: Mirroring FAILED:
Traceback (most recent call last):
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/gdc_mirror.py", line 288, in execute
    self.mirror()
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/gdc_mirror.py", line 137, in mirror
    self.mirror_project(prgm, project)
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/gdc_mirror.py", line 224, in mirror_project
    prev_metadata)
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/gdc_mirror.py", line 281, in mirror_category
    self.__mirror_file(file_d, proj_dir, n+1, num_files)
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/gdc_mirror.py", line 149, in __mirror_file
    savepath = meta.mirror_path(proj_root, file_d, strict=strict)
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/lib/meta.py", line 220, in mirror_path
    name = file_basename(file_dict, strict)
  File "/mnt/gdc-download/venv/local/lib/python2.7/site-packages/gdctools/lib/meta.py", line 203, in file_basename
    raise ValueError("unsupported file type: " + name)
ValueError: unsupported file type: TCGA-BH-A0B7-11A-03-TSC.f0571ac2-0655-42b9-895e-e7b4ddc6d16e.svs
```

**Comment by noblem** [comment]
Thank you for submitting this, Alex.  There is a [commit](https://github.com/broadinstitute/gdctools/commit/3b63cb91762b6b647fc78ea15438920df1de5f37) in master which addresses this, if you'd like to do a pull to your clone?

**Comment by noblem** [comment]
And I just make another beta release, so marking this closed.  Thanks again for the problem report!
