### ISSUE TITLE
problem dicing latest CN data (from 2018_06_13)

### ISSUE THREAD

**Issue by noblem** [broadinstitute/gdctools#76]
2018-07-03 01:09:05,761[INFO]: Dicing file /xchip/gdac_data/gdc/mirror/TCGA/TCGA-ACC/Copy_Number_Variation/Copy_Number_Segment/BLAIN_p_TCGA_282_304_b2_N_GenomeWideSNP_6_D04_1348436.grch38.seg.v2.d38b4850-e280-433b-9964-b4371d8f82ba.txt
2018-07-03 01:09:05,827[ERROR]: Dicing FAILED:
Traceback (most recent call last):
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/gdc_dice.py", line 226, in execute
    self.dice()
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/gdc_dice.py", line 170, in dice
    force=self.force)
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/gdc_dice.py", line 383, in dice_one
    convert(file_dict, mirror_path, dice_path)
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/lib/convert/seg.py", line 22, in process
    writeCsvFile(outfile, seg_file_data)
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/lib/common.py", line 155, in writeCsvFile
    csvfile.writerows(data)
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/lib/convert/seg.py", line 48, in generate_seg_file
    new_row = converter(row, tcga_id, hyb_id)
  File "/xchip/cga_home/mnoble/src/gdctools/gdctools/lib/convert/seg.py", line 89, in seg_broad
    if row['Sample'] != hyb_id:
KeyError: 'Sample'

**Comment by noblem** [comment]
This was addressed in [release v0.2.9](https://github.com/broadinstitute/gdctools/releases/tag/v0.2.9)
